version: 0.2

env:
  variables:
    APP_NAME: "comprehensive-production-ci-cd-pipeline-codepipeline"
    AWS_REGION: "us-east-1"
    AWS_ACCOUNT_ID: "025066251600"
    ECR_REPO_URI: "025066251600.dkr.ecr.us-east-1.amazonaws.com/comprehensive-production-ci-cd-pipeline-codepipeline"
  secrets-manager:
    DOCKERHUB_PASS: "comp-prod-pipeline-secret:dockerhub_pass"
    SONAR_TOKEN: "comp-prod-pipeline-secret:sonar_token_param"
  exported-variables:
    - IMAGE_TAG


phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing dependencies..."
      - apt-get update && apt-get install -y git unzip curl docker.io jq
      - (service docker start || systemctl start docker || nohup dockerd > /dev/null 2>&1 &) && sleep 10
      - for i in $(seq 1 30); do docker info && break || sleep 1; done
      - echo "$DOCKERHUB_PASS" | docker login --username "$DOCKERHUB_USER" --password-stdin || (echo "⚠️ DockerHub login failed" && exit 1)
      - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
      - curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-7.1.0.4889-linux-x64.zip
      - unzip sonar-scanner.zip && mv sonar-scanner-*/ /opt/sonar-scanner && rm sonar-scanner.zip
      - export PATH="/opt/sonar-scanner/bin:$PATH"

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region "$AWS_REGION" | docker login --username AWS --password-stdin "$ECR_REPO_URI"
      - export IMAGE_TAG="$CODEBUILD_BUILD_NUMBER"
      - echo "IMAGE_TAG=$IMAGE_TAG"
      - trivy fs --exit-code 0 --severity HIGH,CRITICAL --skip-dirs target,.git .

  build:
    commands:
      - echo "⚙Building application with Maven..."
      - mvn clean package test dependency:copy-dependencies
      - echo "Building Docker image..."
      - docker build -t "$ECR_REPO_URI:$IMAGE_TAG" .
      - docker tag "$ECR_REPO_URI:$IMAGE_TAG" "$ECR_REPO_URI:latest"

  post_build:
     commands:
      - echo "Starting SonarCloud analysis..."
      - sonar-scanner \
        -Dsonar.projectKey=comprehensive-production-ci-cd-pipeline \
        -Dsonar.organization=mohamedesmael10 \
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.java.binaries=target \
        -Dsonar.java.libraries=target/dependency/*.jar \
        -Dsonar.login=$SONAR_TOKEN

      - echo "Waiting for SonarCloud quality gate result..."
      - sleep 10
      - |
        REPORT=$(curl -s -u "$SONAR_TOKEN": "https://sonarcloud.io/api/qualitygates/project_status?projectKey=comprehensive-production-ci-cd-pipeline")
        STATUS=$(echo "$REPORT" | jq -r '.projectStatus.status')
        if [ "$STATUS" != "OK" ]; then
          echo "Quality gate failed: $STATUS"
          exit 1
        else
          echo " Quality gate passed."
        fi
      - echo "Scanning Docker image with Trivy..."
      - trivy image --exit-code 0 --severity HIGH,CRITICAL "$ECR_REPO_URI:$IMAGE_TAG"
      - echo " Pushing Docker images to ECR..."
      - docker push "$ECR_REPO_URI:$IMAGE_TAG"
      - docker push "$ECR_REPO_URI:latest"

artifacts:
  files:
    - target/*.jar
    - target/dependency/**/*
