version: 0.2

env:
  variables:
    APP_NAME: "comprehensive-production-ci-cd-pipeline-codepipeline"
    AWS_REGION: "us-east-1"
    CLUSTER_NAME: "mohamed-esmael-cluster"
    SERVICE_NAME: "mohamed-esmael-service"
    CONTAINER_NAME: "mohamed-esmael-container"
    AWS_ACCOUNT_ID: "025066251600"
  exported-variables:
    - IMAGE_TAG

phases:
  install:
    commands:
      - apt-get update
      - apt-get install -y ansible git jq

  pre_build:
    commands:
      - set -eu
      - |
        if [ -f image_tag.txt ]; then
          export IMAGE_TAG="$(cat image_tag.txt | tr -d '\r\n')"
          echo "Using IMAGE_TAG from file: $IMAGE_TAG"
        else
          export IMAGE_TAG="latest"
          echo "image_tag.txt not found, using fallback: $IMAGE_TAG"
        fi
      - export ECR_REPO_URI="025066251600.dkr.ecr.us-east-1.amazonaws.com/comprehensive-production-ci-cd-pipeline-codepipeline"


  build:
    commands:
      - echo "Fetching current ECS task definition..."
      - aws ecs describe-task-definition --task-definition "$SERVICE_NAME" > task-def.json
      - |
        echo "Updating task definition with new image..."
        NEW_TASK_DEF=$(jq --arg IMAGE "$ECR_REPO_URI:$IMAGE_TAG" --arg CONTAINER_NAME "$CONTAINER_NAME" '
          .taskDefinition | {
            family,
            containerDefinitions: (
              .containerDefinitions | map(
                if .name == $CONTAINER_NAME then .image = $IMAGE else . end
              )
            ),
            requiresCompatibilities,
            cpu,
            memory,
            networkMode,
            executionRoleArn,
            taskRoleArn,
            volumes,
            placementConstraints
          }' task-def.json)
        echo "$NEW_TASK_DEF" > new-task-def.json
      - |
        echo "Registering new task definition..."
        export REVISION=$(aws ecs register-task-definition --cli-input-json file://new-task-def.json | jq -r '.taskDefinition.revision')
        echo "New task definition revision: $REVISION"

  post_build:
    commands:
      - echo "Updating ECS service..."
      - aws ecs update-service --cluster "$CLUSTER_NAME" --service "$SERVICE_NAME" --task-definition "${SERVICE_NAME}:$REVISION"

artifacts:
  files:
    - image_tag.txt
