apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-ci-cd-pipeline
spec:
  replicas: 2
  selector:
    matchLabels:
      app: production-ci-cd-pipeline  
  template:
    metadata:
      labels:
        app: production-ci-cd-pipeline  
    spec:
      containers:
        - name: production-ci-cd-pipeline
          image: mohamedesmael/comprehensive-production-ci-cd-pipeline-github-actions:1.0.0-59
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m" 
          ports:
            - containerPort: 8080
