pipeline {
    agent {
        label "jenkins-agent"
    }

    environment {
        APP_NAME = "comprehensive-production-ci-cd-pipeline"
    }

    stages {
        stage("Cleanup Workspace") {
            steps {
                cleanWs()
            }
        }

        stage("Checkout from SCM") {
            steps {
                git branch: 'main', credentialsId: 'github', url: 'https://github.com/mohamedesmael10/comprehensive-production-ci-cd-pipeline'
            }
        }

        stage("Update the Deployment Tags") {
            steps {
                sh """
                cd argocd
                ls -l
                cat deployment.yaml
                sed -i 's/${APP_NAME}.*/${APP_NAME}:${IMAGE_TAG}/g' deployment.yaml
                cat deployment.yaml
                """
            }
        }

        stage("Push the changed deployment file to Git") {
            steps {
                sh """
                git config --global user.name "mohamedesmael10"
                git config --global user.email "mohamed.2714104@gmail.com"
                git add argocd/deployment.yaml
                git commit -m "Updated Deployment Manifest"
                """

                withCredentials([gitUsernamePassword(credentialsId: 'github', gitToolName: 'Default')]) {
                    sh 'git push https://github.com/mohamedesmael10/comprehensive-production-ci-cd-pipeline main'
                }
            }
        }

        stage("Deploy Monitoring Stack") {
            agent {
                label "jenkins-agent"
            }
            steps {
                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                    sh """
                    ansible-playbook Ansible/deploy_monitoring.yaml
                    """
                }
            }
        }
    }
}
