pipeline {
    agent {
        label "jenkins-agent"
    }

    environment {
        APP_NAME = "comprehensive-production-ci-cd-pipeline"
    }

    stages {
        stage("Cleanup Workspace") {
            steps {
                cleanWs()
            }
        }

        stage("Checkout from SCM") {
            steps {
                git branch: 'main',
                    credentialsId: 'github',
                    url: 'https://github.com/mohamedesmael10/comprehensive-production-ci-cd-pipeline'
            }
        }

        stage("Update the Deployment Tags") {
            steps {
                sh """
                cd argocd
                ls -l
                cat deployment.yaml
                sed -i 's/${APP_NAME}.*/${APP_NAME}:${IMAGE_TAG}/g' deployment.yaml
                cat deployment.yaml
                """
            }
        }

        stage("Push the changed deployment file to Git") {
            steps {
                sh """
                git config --global user.name "mohamedesmael10"
                git config --global user.email "mohamed.2714104@gmail.com"
                git add argocd/deployment.yaml
                git commit -m "Updated Deployment Manifest"
                """
                withCredentials([usernamePassword(credentialsId: 'github', usernameVariable: 'GIT_USER', passwordVariable: 'GIT_PASS')]) {
                    sh 'git push https://${GIT_USER}:${GIT_PASS}@github.com/mohamedesmael10/comprehensive-production-ci-cd-pipeline main'
                }
            }
        }

        stage("Deploy Monitoring Stack") {
            agent {
                label "jenkins-agent"
            }
            steps {
                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                    sh """
                    ansible-playbook Ansible/deploy_monitoring.yaml
                    """
                }
            }
        }
    }

    post {
        failure {
            mail(
                subject: "${env.JOB_NAME} - Build #${env.BUILD_NUMBER} - Failed",
                body: """
The deployment pipeline failed.

You can view the build details here:
${env.BUILD_URL}

Please check the Jenkins console output for more information.
""",
                to: "mohamed.2714104@gmail.com"
            )
        }

        success {
            mail(
                subject: "${env.JOB_NAME} - Build #${env.BUILD_NUMBER} - Successful",
                body: """
The deployment pipeline completed successfully.

You can view the build details here:
${env.BUILD_URL}

You can proceed with the next steps.
""",
                to: "mohamed.2714104@gmail.com"
            )
        }
    }
}
