---
- name: Setup monitoring stack on local machine
  hosts: localhost
  connection: local
  become: true  
  
  tasks:
    - name: Setup cAdvisor and Jenkins
      script: prometheus/setup_cadvisor_and_jenkins.sh
      become: true
      ignore_errors: yes  
      
    - name: Setup Node Exporter
      script: prometheus/setup_node_exporter.sh
      become: true
      ignore_errors: yes

    - name: Setup Grafana
      script: prometheus/setup_grafana.sh
      become: true
      ignore_errors: yes

