---
- name: Deploy Monitoring Stack (Prometheus, Grafana, ELK, CloudWatch) on EKS
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    namespace: mohamed-esmael-namespace
    cluster_name: mohamed-esmael-cluster-v2
    region: us-east-1

  tasks:

    - name: Ensure Helm repos are added
      shell: |
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        helm repo add grafana https://grafana.github.io/helm-charts
        helm repo add elastic https://helm.elastic.co
        helm repo update

    - name: Install Prometheus
      shell: |
        helm upgrade --install prometheus prometheus-community/prometheus \
          --namespace {{ namespace }} --create-namespace

    - name: Install Grafana
      shell: |
        helm upgrade --install grafana grafana/grafana \
          --namespace {{ namespace }} --create-namespace

    - name: Install Elasticsearch
      shell: |
        helm upgrade --install elasticsearch elastic/elasticsearch \
          --namespace {{ namespace }} --create-namespace

    - name: Install Kibana
      shell: |
        helm upgrade --install kibana elastic/kibana \
          --namespace {{ namespace }}

    - name: Associate IAM OIDC provider with EKS (required for CloudWatch agent)
      shell: |
        eksctl utils associate-iam-oidc-provider \
          --region {{ region }} \
          --cluster {{ cluster_name }} \
          --approve

    - name: Download Fluent Bit config for CloudWatch
      get_url:
        url: https://raw.githubusercontent.com/aws/containers-roadmap/master/preview-programs/observability/aws-cloudwatch/cloudwatch-logs/fluent-bit/fluent-bit.yaml
        dest: /tmp/fluent-bit.yaml

    - name: Apply Fluent Bit config to EKS
      shell: |
        kubectl apply -f /tmp/fluent-bit.yaml -n {{ namespace }}
