name: CI Pipeline (GitHub Actions)

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release version'
        required: false
        default: '1.0.0'

env:
  APP_NAME: comprehensive-production-ci-cd-pipeline-github-actions

jobs:
  setup-apache:
    name: Provision Apache on Server
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup workspace
        run: |
          if [ -d .git ]; then
            git clean -fdx
          else
            echo "No .git directory found, skipping cleanup."
          fi

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          ref: git-actions-pipeline
      
      - name: Run setup-apache.sh directly
        run: |
          curl -fsSL \
            https://raw.githubusercontent.com/mohamedesmael10/comprehensive-production-ci-cd-pipeline/git-actions-pipeline/apache_configs/setup-apache.sh \
            -o /tmp/setup-apache.sh

          chmod +x /tmp/setup-apache.sh
          sudo /tmp/setup-apache.sh
          env:
          DNS_EXIT_API_KEY: ${{ secrets.DNS_EXIT_API_KEY }}

  build-and-scan:
    name: Build & Static Scans
    needs: setup-apache
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup workspace
        run: git clean -fdx

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Trivy File Scan
        uses: aquasecurity/trivy-action@v0
        with:
          scan-type: fs
          scan-path: '.'
          exit-code: 0
          severity: HIGH,CRITICAL
          skip-dirs: target,.git

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Compile & Package
        run: mvn clean package

      - name: Execute Unit Tests
        run: mvn test

      - name: SonarCloud Analysis
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONARTOKEN }}
          SONAR_HOST_URL: https://mohamedesmaelsonarqube.work.gd

      - name: SonarQube Quality Gate check
        id: quality-gate
        uses: SonarSource/sonarqube-quality-gate-action@v1.2.0
        with:
          pollingTimeoutSec: 600
        env:
          SONAR_TOKEN: ${{ secrets.SONARTOKEN }}
          SONAR_HOST_URL: https://mohamedesmaelsonarqube.work.gd

  docker:
    name: Build, Scan & Push Image
    needs: build-and-scan
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup workspace
        run: git clean -fdx

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build & Tag Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: |
            ${{ secrets.DOCKER_USER }}/${{ env.APP_NAME }}:${{ github.event.inputs.release }}-${{ github.run_number }}
            ${{ secrets.DOCKER_USER }}/${{ env.APP_NAME }}:latest

      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@v0
        with:
          scan-type: image
          image-ref: ${{ secrets.DOCKER_USER }}/${{ env.APP_NAME }}:latest
          exit-code: 0
          severity: HIGH,CRITICAL

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USER }}/${{ env.APP_NAME }}:${{ github.event.inputs.release }}-${{ github.run_number }}
          docker push ${{ secrets.DOCKER_USER }}/${{ env.APP_NAME }}:latest

  trigger-cd:
    name: Trigger CD Workflow
    if: github.event.inputs.run_cd == 'true'
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup workspace
        run: git clean -fdx

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Trigger CD via GitHub API
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            https://api.github.com/repos/mohamedesmael10/comprehensive-production-ci-cd-pipeline/git-actions-pipeline/actions/workflows/cd-pipeline.yml/dispatches \
            -d '{"ref":"git-actions-pipeline","inputs":{"image_tag":"${{ github.event.inputs.release }}-${{ github.run_number }}"}}'
